controllers/contrato_controller.py
from flask import request, redirect, url_for, Blueprint, session, flash
from datetime import datetime
from functools import wraps
from models.contrato_model import Contrato
from models.asignacion_model import Asignacion
from models.usuario_model import Usuario
import os
from flask import send_from_directory, current_app
from controllers.acceso_controller import requiere_login

from views import contrato_view

contrato_bp = Blueprint("contrato", __name__, url_prefix="/contratos")

@contrato_bp.route("/")
@requiere_login
def index():
    # Recuperar todos los registros de productos
    contratos = Contrato.get_all()
    return contrato_view.list(contratos)

@contrato_bp.route("/search", methods=["GET"])
@requiere_login
def search():
    q = request.args.get("q", "").strip()
    if not q:
        return redirect(url_for("contrato.index"))
    
    contratos = Contrato.query.filter(
        (Contrato.fecha.ilike(f"%{q}%"))
    ).order_by(Contrato.fecha.asc()).all()

    return contrato_view.list(contratos)


@contrato_bp.route("/create", methods=["GET", "POST"])
@requiere_login
def create():
    if request.method == "POST":
        usuario_id = request.form.get("usuario_id")
        asignacion_id = request.form.get("asignacion_id")
        fecha = datetime.strptime(request.form["fecha"], "%Y-%m-%d").date()
        condiciones = request.form["condiciones"]

        contrato = Contrato(
            usuario_id=usuario_id,
            asignacion_id=asignacion_id,
            fecha=fecha,
            condiciones=condiciones
        )
        contrato.save()
        generar_pdf(contrato.id)
        flash("Registro guardado exitosamente", "success")
        return redirect(url_for("contrato.index"))

    usuarios = Usuario.query.all()
    asignaciones = Asignacion.query.all()
    
    return contrato_view.create( asignaciones,usuarios)


@contrato_bp.route("/edit/<int:id>", methods=["GET", "POST"])
@requiere_login
def edit(id):
    contrato = Contrato.get_by_id(id)
    if request.method == "POST":
        usuario_id = request.form["usuario_id"]
        asignacion_id = request.form.get("asignacion_id") or None
        fecha = datetime.strptime(request.form["fecha"], "%Y-%m-%d").date()
        condiciones = request.form["condiciones"]
        
        # Actualizar
        contrato.update(
            usuario_id=usuario_id,
            asignacion_id=asignacion_id,
            fecha=fecha,
            condiciones=condiciones
        )
        flash("Registro actualizado correctamente", "warning")
        return redirect(url_for("contrato.index"))

    usuarios = Usuario.query.all()
    asignaciones = Asignacion.query.filter(Asignacion.espacio != None).all()


    return contrato_view.edit(contrato, asignaciones, usuarios)


@contrato_bp.route("/delete/<int:id>")
@requiere_login
def delete(id):
    contrato = Contrato.get_by_id(id)
    contrato.delete()
    flash("Registro eliminado correctamente", "danger")
    return redirect(url_for("contrato.index"))


@contrato_bp.route("/ver/<int:id_contrato>")
@requiere_login
def ver_contrato(id_contrato):
    pdf_dir = os.path.join(current_app.root_path, "static", "contratos")
    filename = f"contrato_{id_contrato}.pdf"

    if not os.path.exists(os.path.join(pdf_dir, filename)):
        return "El contrato no existe.", 404
    
    return send_from_directory(pdf_dir, filename)


# funcion para generar PDF del contrato
def generar_pdf(id):
    from utils.pdf_contratos import generar_pdf_contrato
    ruta = generar_pdf_contrato(id)
    return redirect(url_for('static', filename=ruta))

views/contrato_view.py
from flask import render_template

def list(contratos):
    return render_template('contratos/index.html', contratos = contratos)

def create(asignaciones,usuarios):
    # Se requiere tipo_contratos y asignaciones
    return render_template('contratos/create.html', asignaciones = asignaciones, usuarios = usuarios)

def edit(contrato, asignaciones,  usuarios,):
    return render_template('contratos/edit.html',contrato=contrato, asignaciones=asignaciones, usuarios=usuarios)

templates/contratos/create.html
{% extends "base.html" %}

{% block title %}Nueva Contrato{% endblock %}

{% block content %}
<div class="form-container">
    <div class="form-card">
        <h2 class="form-title">Nueva Contrato</h2>

        <form action="{{ url_for('contrato.create') }}" method="POST" class="cliente-form"
            enctype="multipart/form-data">

            <div class="input-group mb-3">
                <label class="form-label">Usuario</label>
                <input type="text" class="form-input" value="{{ session['usuario_nombre'] }}" readonly>

                <!-- ✔ Campo real que se enviará al servidor -->
                <input type="hidden" name="usuario_id" value="{{ session['usuario_id'] }}">
            </div>

            <div class="input-group mb-3">
                <label for="asignacion" class="form-label">Espacio</label>
                <select name="asignacion_id" class="form-input" required>
                    <option value="">Seleccione un espacio</option>

                    {% for asignacion in asignaciones %}
                    <option value="{{ asignacion.id }}">
                        {{ asignacion.espacio.ubicacion }}
                    </option>
                    {% endfor %}
                </select>

            </div>


            <div class="input-group mb-3">
                <label for="fecha" class="form-label">Fecha del contrato</label>
                <input type="date" class="form-input" name="fecha" required>
            </div>


            <div class="input-group mb-3">
                <label for="Condiciones" class="form-label">Condiciones</label>
                <input type="text" class="form-input" name="condiciones" required>
            </div>

            <button type="submit" class="btn-guardar">Guardar</button>
        </form>
    </div>
</div>
{% endblock %}

templates/contratos/index.html
{% extends "base.html" %}
{% block title %}Contratos{% endblock %}

{% block content %}
<h3>Gestión de Contratos</h3>

<div class="btn-opciones d-flex justify-content-between align-items-center mb-2" style="gap: 10px;">
    <a href="{{ url_for('contrato.create') }}" class="btn btn-sm btn-success" title="Nuevo"
        style="display: flex; align-items: center; gap: 5px; padding: 8px;">
        <i class="bi bi-plus-circle"></i> Nuevo
    </a>
    <form method="get" action="{{ url_for('contrato.search')}}" class="d-flex align-items-center"
        style="max-width: 500px; gap: 5px;">
        <input type="date" name="q" class="form-input" value="{{ query or '' }}" style="padding:6px;">
        <button type="submit" class="btn btn-primary">Buscar</button>
    </form>
</div>

<table id="AllTable" class="table table-striped table-hover">
    <thead class="table-dark">
        <tr>
            <th>ID</th>
            <th>Usuario</th>
            <th>Espacio</th>
            <th>Responsable</th>
            <th>Fecha de contrato</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        {% for contrato in contratos %}
        <tr>
            <td>{{ contrato.id }}</td>
            <td>{{ contrato.usuario.nombre}}</td>
            <td>{{ contrato.asignacion.espacio.ubicacion }}</td>
            <td>{{ contrato.asignacion.responsable }}</td>
            <td>{{ contrato.fecha.strftime('%d/%m/%Y') }}</td>
            <td class="text-center">
                <a href="{{ url_for('contrato.ver_contrato', id_contrato=contrato.id) }}" target="_blank"
                    class="btn btn-sm btn-primary btn-sm rounded-pill btn-pdf">
                    <i class="bi bi-file-earmark-pdf"></i> Ver Contrato
                </a>
                <a href="{{ url_for('contrato.delete', id=contrato.id) }}" class="btn btn-danger btn-sm rounded-pill"
                    onclick="return confirm('¿Seguro que deseas eliminar este registro?');">
                    <i class="bi bi-trash3"></i> Eliminar
                </a>
            </td>
        </tr>
        {% else %}
        <tr>
            <td colspan="10" class="text-muted text-center">No hay registros.</td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<!-- Contenedor de paginación -->
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-end" id="pagination"></ul>
</nav>

{% endblock %}

{% block scripts %}
<script src="{{ url_for('static', filename='js/scripts.js') }}"></script>
{% endblock %}